# Generated by Django 4.1.3 on 2022-12-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sal',
            field=models.IntegerField(),
        ),
    ]
